name: Build
on: [push]
jobs:
  publish-vsce:
    name: Publish to Visual Studio Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish -p ${{ secrets.vsce_token }}
  publish-github:
    name: Publish to GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - name: Package extension
        run: |
          mkdir dist
          npx vsce package -o dist/<%= repoName %>-${GITHUB_REF/refs\/tags\//}.vsix
      - name: Upload extension to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
