name: Publish
on:
  push:
    tags:
      - v*.*.*
jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.github_auth_token }}
  publish-vsce:
    name: Publish to Visual Studio Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        run: yarn
      - name: Publish to Visual Studio Marketplace
        run: yarn vsce publish -p ${{secrets.vsce_token}}
  publish-github:
    name: Publish to GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        run: yarn
      - name: Package extension
        run: |
          mkdir dist
          yarn vsce package -o dist/one-dark-theme-${GITHUB_REF/refs\/tags\//}.vsix
      - name: Upload extension to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_auth_token }}
